-- Calculate Engagements
-- IN: Post_ID
-- OUT: Total engagements for post (all types)

SELECT * FROM Engagements;
DELIMITER //
CREATE FUNCTION Calculate_Engagements(
    POST_TO_FIND INT)
RETURNS INT 
DETERMINISTIC
BEGIN
	DECLARE TOTAL_ENGAGEMENTS INT DEFAULT 0;
	SELECT COUNT(Engagements.POST_ID) INTO TOTAL_ENGAGEMENTS
    FROM Engagements 
		WHERE Engagements.POST_ID = POST_TO_FIND
	GROUP BY Engagements.POST_ID;
	RETURN TOTAL_ENGAGEMENTS;
END //
DELIMITER ;

SELECT Posts.POST_ID, Calculate_Engagements(Posts.POST_ID) as TOTAL_ENGAGEMENT
FROM Posts;

-- Calculate Followers
-- IN: Account_ID
-- OUT: Total Followers

DELIMITER //
CREATE FUNCTION Calculate_Followers(
    ACCOUNT_ID INT)
RETURNS INT 
DETERMINISTIC
BEGIN
	DECLARE TOTAL_FOLLOWERS INT DEFAULT 0;
	SELECT COUNT(User_Following.FOLLOWING_ACCOUNT_ID) INTO TOTAL_FOLLOWERS
    FROM User_Following
		WHERE User_Following.ACCOUNT_ID = ACCOUNT_ID
	GROUP BY  User_Following.ACCOUNT_ID;
	RETURN TOTAL_FOLLOWERS;
END //
DELIMITER ;

-- Calculate Following
-- IN: Account_ID
-- OUT: Total Followers

DELIMITER //
CREATE FUNCTION Calculate_Following(
    ACCOUNT_ID INT)
RETURNS INT 
DETERMINISTIC
BEGIN
	DECLARE TOTAL_FOLLOWING INT DEFAULT 0;
	SELECT COUNT(User_Following.FOLLOWING_ACCOUNT_ID) INTO TOTAL_FOLLOWING
    FROM User_Following
		WHERE User_Following.FOLLOWING_ACCOUNT_ID = ACCOUNT_ID
	GROUP BY  User_Following.FOLLOWING_ACCOUNT_ID;
	RETURN TOTAL_FOLLOWING;
END //
DELIMITER ;

-- User_Age
-- IN: Birthday
-- Out: User's age today

DELIMITER //
CREATE FUNCTION User_Age (
	BIRTHDAY DATETIME)
RETURNS INT
DETERMINISTIC
BEGIN 
	DECLARE AGE INT;
    SET AGE = TRUNCATE((DATEDIFF(NOW(),BIRTHDAY)/365),0);
    RETURN AGE;
END // 
DELIMITER ;
